### PR TITLE
Adds component migration and fixes sqlite3 depends

### LINKED ISSUE #44: Component field relations dissappearing during the migration process
## Bug report

Hello and thanks for the hard work with the migration scripts! This is my first PR so let me know in case there is something unclear. Also steps 5. and 8. are something that could raise another issue, but I think that the most critical and valuable thing to solve is the described issue.

### Required System information

- Node.js version: 14 on v3, 16 on v4
- NPM version: 7.20.3
- Source Strapi version: 4.3.8
- Target Strapi version: 3.5.1
- Source Database: sqlite
- Target Database: sqlite
- Operating system: osx
- Which script are you running: [v3-sql-v4-sql](https://github.com/strapi/migration-scripts/tree/main/v3-sql-v4-sql)

### Describe the bug

Component field relations are dissappearing during the migration process

### Steps to reproduce the behavior

1. `npx create-strapi-app@3.5.1 reproductible-relation-error`
2. Create following things in the admin panel:

* Collection Tools
   * name (string)
* Component Toolbox with fields
   * tools (relation with tools)
      * one toolbox can have multiple tools
* Collection Carpenter
   * name (string)
   * Toolbox (repeatable component)

3. Add some carpenters with toolboxes that contain tools
4. Do [migration to strapi v4](https://strapi.io/blog/how-to-migrate-from-strapi-v3-to-v4-walkthrough)
5. Remove [fields from strapi_permission in the DB](https://github.com/strapi/migration-scripts/issues/19#issuecomment-1228996060)
6. Run the v3-sql-v4-sql migration script
7. Encounter `Cannot read property 'fields' of null` error
8. On table `admin_permissions` change the `null` fields to `{}` in the column `properties`
9. Everything runs nicely
10. Witness that the component relations have disappeared from v4 DB

### Expected behavior

Component relations should migrate to v4

### Screenshots

To visualize the collections:

Screenshot 2022-09-16 at 15 58 28

Screenshot 2022-09-16 at 15 58 23

V3 API returns:

Screenshot 2022-09-16 at 15 57 48

V4 API returns:

image

V3 database structure seems to show the components_element_stores__tools 

Screenshot 2022-09-16 at 16 44 25

but the V4 seems to have discarded it

image

### Code snippets

-

### Additional context

I'm happy to provide the v3 and v4 databases if needed

### PR DESCRIPTION
**Pull request by derrickmehaffy**
## What this PR does

- [x] Creates a new migration for components (yes it's in the api folder migration, I don't want to change it)
- [x] Handles component relations and migrates them to v4
- [x] Swaps out `sqlite3` depends for `better-sqlite3`

## How to test

- Create a content-type that contains a component
- Component should have a relation
- Run migration and validated the component's relation is properly migrated to v4 syntax

fixes #44

### CODE REVIEW

File: lib/v4/migration-helpers/convert-components.js [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+const getRelationObject = require('./get-relation-object');
+
+/**
+ * @description Migrates component json to v4 structure with nested relations
+ *
+ * @param {string} componentsPath Path to the components folder
+ * @param {string} componentName Name of the current component
+ */
+const convertComponent = async (componentsPath, componentCategory, componentName) => {
+  console.log(componentsPath)
```
Comment (markkaylor) [inline lib/v4/migration-helpers/convert-components.js:19]: 👀

File: lib/v4/migration-helpers/convert-components.js [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+          attribute = getRelationObject('oneToMany', { ...attribute, inversed: false });
+        } else {
+          logger.warn(`unknown relation type, please fix manually: ${key}`);
+        }
+
+        _.set(componentJson, `attributes.${key}`, attribute);
+      });
+    }
+
+    // Create the new content-types/api/schema.json file
```
Comment (GregorSondermeier) [inline lib/v4/migration-helpers/convert-components.js:96]:
```suggestion
    // Create the new component.json file
```

File: lib/v4/migration-helpers/convert-components.js [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+    await fs.ensureFile(componentsPath);
+    // Write modified JSON to schema.json
```
Comment (GregorSondermeier) [inline lib/v4/migration-helpers/convert-components.js:98]:
```suggestion
    // Write modified JSON to component.json
```

**Review by GregorSondermeier — COMMENTED** [review]
Thanks for addressing my comments!

**Review by markkaylor — COMMENTED** [review]
Great work @derrickmehaffy! Looks like this is working, sorry it took me a while to get to the review. I think we just need to fix / update the tests then we can merge and do a release.

**Comment by derrickmehaffy** [comment]
Yup I'll work on fixing the tests now

**Review by markkaylor — APPROVED** [review]
